apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  type: ClusterIP
  selector:
    app: envoy
  ports:
    - name: http
      port: 8080
      targetPort: 8080

    - name: admin
      port: 9901
      targetPort: 9901

