# dev/kind/cluster.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080    # Envoy の外部公開用
      - containerPort: 30000
        hostPort: 30000    # NodePort テスト用（任意）
  - role: worker
  - role: worker

